language: python

python:
  - "3.6"

sudo:
    required

addons:
    firefox: "45.0"

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

install:
    - "pip install -r backend/requirements.txt"

before_script:
  - "cd backend;"

script:
    - "python manage.py test"