FROM python:3

ENV PYTHONBUFFERED 1

RUN mkdir /code
WORKDIR /code
ADD ./backend/requirements.txt /code/
RUN pip install -r requirements.txt
ADD ./backend /code/

RUN python manage.py migrate
RUN python manage.py loaddata 002fixture.json

CMD python manage.py runserver
