FROM python:3

ENV PYTHONBUFFERED 1

# https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/gunicorn/#running-django-in-gunicorn-as-a-generic-wsgi-application
RUN pip install gunicorn

RUN mkdir /code
WORKDIR /code
ADD ./requirements.txt /code/
RUN pip install -r requirements.txt
ADD ./ /code/